### ISSUE TITLE
Changing Database Architecture 

### ISSUE THREAD

**Issue by Hugo-Pare** [market-sentiment-analyzer-tool/msat#17]
Update `db` directory, refactor in folders:
```
db:
  reddit:
    reddit_schema.sql
    reddit_nvda_data.sql
    reddit_aapl_data.sql
    ...
  news:
    news_schema.sql
    news_nvda_data.sql
    news_aapl_data.sql
    ...
```
- Create DB to collect news data
- Make it scalable for other companies/tickers, add Apple (AAPL) to DB
- Will affect docs, tests, scrapers (but will fix later)

**Comment by Jayden-uottawa** [comment]
db:
Schema.sql
  reddit:
    reddit_nvda_data.sql
    reddit_aapl_data.sql
    ...
  news:
    news_nvda_data.sql
    news_aapl_data.sql
    ...

**Comment by Hugo-Pare** [comment]
Changed DB architecture, will need to update it for Reddit
