### ISSUE TITLE
User Interface makeover

### ISSUE THREAD

**Issue by Hugo-Pare** [market-sentiment-analyzer-tool/msat#31]
Connect UI with API, search bar with stock tickers, weight filter for Reddit/News ratio

**Comment by Jayden-uottawa** [comment]
Added a table to display the top 4 post or news from the Database

**Comment by Jayden-uottawa** [comment]
Modified the search bar to have the available stock option. Still need to change css to make it more appeling

**Comment by Jayden-uottawa** [comment]
Added the table for Yahoo and Twitter and implemented that if there is no data a message is shown

**Comment by Jayden-uottawa** [comment]
Added dynamic searching the search bar propose stocks based on what is typed

**Comment by Jayden-uottawa** [comment]
Implementing PieChart to visibly see the weights of different sources

**Comment by Jayden-uottawa** [comment]
Calculating the cumulative sentiment score based on the weight and the score of each source.

**Comment by Jayden-uottawa** [comment]
Implemented to have the full title instead of NVDA -> NVIDIA Corporation (NVDA) Sentiment Analysis
Enhanced weight inputs to make a form and make it look better
Added Css for search bar to make it more appeling

**Comment by Jayden-uottawa** [comment]
Still need to:
- Add spacing between title and range bar
-

**Comment by Jayden-uottawa** [comment]
Fixed cumulative score to have 4 decimals instead of 2
