### ISSUE TITLE
Add Sentiment feature to UI

### ISSUE THREAD

**Issue by Hugo-Pare** [market-sentiment-analyzer-tool/msat#58]
Adding a UI feature where users can test/play around with the Sentiment Analyzer directly on the UI
Will not be stored
How to call the endpoint:
```python
# Using Python requests
import requests
response = requests.get(
    'http://localhost:5000/sentiment',
    params={'text': 'This stock is such a SELL!!'}
)
print(response.json())
```

**Comment by Jayden-Bergevin** [comment]
Added this feature to the UI

**Comment by Jayden-Bergevin** [comment]
Incorperated the background to be the same color as sentiment range
