### ISSUE TITLE
Extra fixes to UI before presentation

### ISSUE THREAD

**Issue by Hugo-Pare** [market-sentiment-analyzer-tool/msat#61]
- Center or enlarge the search bar to make it symmetrical
- Change order of Media sources in the weight box to follow the same order as the tables
- Make the input box of the sentiment explorer fill the width of the box
- Possibly show the sentiment result of the explorer on the right of the analyze button

**Comment by Jayden-Bergevin** [comment]
[ ] Center or enlarge the search bar to make it symmetrical
[ ] Change order of Media sources in the weight box to follow the same order as the tables
[ ] Make the input box of the sentiment explorer fill the width of the box
[ ] Possibly show the sentiment result of the explorer on the right of the analyze button
