### ISSUE TITLE
Add data from workflow to the db

### ISSUE THREAD

**Issue by Jayden-uottawa** [market-sentiment-analyzer-tool/msat#8]

**Comment by Jayden-uottawa** [comment]
The data from the workflow is currently being only outputed in the workflow. We need to be able to add this data to the db.

**Comment by Jayden-uottawa** [comment]
The idea is to have a JSON file for the news_data. The workflow will add the data to the JSON file and the it will commit changes and push to main branch. We will than have a script that will take the data from the JSON and add it to the db. The script will check for lines that are already there and will clean the JSON file as it adds them to the db to keep the JSON as small as possible.

**Comment by Hugo-Pare** [comment]
Adopted a different approach
